### ISSUE TITLE
Missing opens directive in module descriptor

### ISSUE THREAD

**Issue by sormuras** [junit-pioneer/junit-pioneer#539] opened 2021-11-14 15:59 UTC
### Problem

Using Pioneer on the module path fails with:

```text
java.lang.reflect.InaccessibleObjectException:
  Unable to make org.junitpioneer.jupiter.IssueExtension() accessible:
  module org.junitpioneer does not "opens org.junitpioneer.jupiter" to module org.junit.platform.commons
```

when using an extension located in package `org.junitpioneer.jupiter`.

### Possible Solution

Open packages that contain types using JUnit Platform's reflection support to module `org.junit.platform.commons`.

```java
  opens org.junitpioneer.jupiter to org.junit.platform.commons;
```

### Work around

Pass `--add-opens org.junitpioneer/org.junitpioneer.jupiter=org.junit.platform.commons` on the command-line or at the right place of your build tool when

**Comment by sormuras** [comment] 2021-11-14 16:17
Find an external reproducer here: https://github.com/junit-team/junit5-samples/compare/sormuras/use-junit-pioneer

Would be better if there was an integration test within Pioneer's build asserting it can be consumed on the module path.

**Comment by sormuras** [comment] 2021-11-14 17:06
🤔

I wonder whether Jupiter may provide a better way when trying to instantiate 3rd-party extensions. From the stack trace...

```text
    MethodSource [className = 'extra.modular.PioneerTests', methodName = 'test', methodParameterTypes = '']
    => java.lang.reflect.InaccessibleObjectException: Unable to make org.junitpioneer.jupiter.StopwatchExtension() accessible: module org.junitpioneer does not "opens org.junitpioneer.jupiter" to module org.junit.platform.commons
       ...
       java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:182)
       org.junit.platform.commons@1.8.1/org.junit.platform.commons.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:1695)
       org.junit.platform.commons@1.8.1/org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:550)
       org.junit.platform.commons@1.8.1/org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:525)
       org.junit.jupiter.engine@5.8.1/org.junit.jupiter.engine.extension.MutableExtensionRegistry.registerExtension(MutableExtensionRegistry.java:145)
```

...you can see, that Jupiter Engine detected an extenion type and asks the JUnit Platform to create an instance of that extension. That's why 3rd-party code, here Pioneer, needs to allow JUnit Platform Commons to reflect deeply into their packages containing extension types.

If the module descriptor (of Pioneer) contained a list of service implemenetations for each extension it ships, like:

```java
  provides org.junit.jupiter.api.extension.Extension with
    ...
    org.junitpioneer.jupiter.IssueExtension,
    org.junitpioneer.jupiter.StopwatchExtension,
    ...;
```

Jupiter should be able to access those extension without the opens directive.

**Comment by sormuras** [comment] 2021-11-15 07:24
Making `IssueExtension`, `StopwatchExtension`, and friends `public` should also do the trick.

**Comment by filiphr** [comment] 2021-11-15 09:30
If the path of using service implementations is taken then there is the chance that Jupiter will auto detect those extensions automatically if the user has explicitly enabled that through a property. I am not sure that this is entirely desirable.

**Comment by sormuras** [comment] 2021-11-15 09:47
Sure, there needs to be some (late) filtering in place in order to not register all provided impls only because a single extension wants to get registered locally. On Java 8 that filtering would basically result in instantiating all `Extension`-implementing instances just to find the one we are looking for, on Java 9+ a lazy stream using [ServiceLoader.Provider](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/ServiceLoader.Provider.html) could be used here to speed up things.

Having said this, adding `opens org.junitpioneer.jupiter to org.junit.platform.commons;` to Pioneer's module descriptor is the way, methinks.

**Comment by beatngu13** [comment] 2021-12-04 00:24
Pushed a fix to [`539-fix-module-descriptor`](https://github.com/junit-pioneer/junit-pioneer/compare/issue/539-fix-module-descriptor). However, need to add a proper IT.

**Comment by nipafx** [comment] 2021-12-23 16:52
The best test for whether Pioneer works on the module path is probably to "just" run the entire build on the module path since those tests use our extensions. Don't we already do that? Although if we do, we already need to have `--add-opens` in play because Jupiter needs to find our tests and they are in the same packages as the code that trips the exception above.

Someone should investigate...

**Comment by beatngu13** [comment] 2022-02-15 12:29
JPMS noob here, so please bear with me...

>Don't we already do that?

While there's indeed `modularBuild`:

https://github.com/junit-pioneer/junit-pioneer/blob/main/build.gradle.kts#L26

Could it be that this has no effect when it comes to testing, as we still test on the classpath? Relevant section from the Gradle docs:

https://docs.gradle.org/7.3/userguide/java_testing.html#sec:java_testing_modular

So, what currently do is whitebox unit testing on the classpath. But what we actually want is to run our tests on the module path.

**Comment by nipafx** [comment] 2022-02-17 20:23
> So, what we currently do is whitebox unit testing on the classpath. But what we actually want is to run our tests on the module path.

I agree. Is there a chance to do that with Gradle, though?

If we can't maybe we can (ab)use [the demo project](https://github.com/junit-pioneer/junit-pioneer-demo) I recently created to reproduce this error and test out the fix (it's configured for Gradle and Maven). That would of course be a manual process, but at least we'd have code in our repos that can validate the fix.

**Comment by aepfli** [comment] 2022-02-17 20:30
we could setup own gradle project within our project and try to use the gradle testkit - i mean this is like executing a gradle build just with a GradleRunner within a unittest - we could even provide multiple tests for that (just ideas, i only used that for testing gradle plugins)

**Comment by beatngu13** [comment] 2022-02-18 21:29
How about this: I will open a PR with the fixes. If we come up with a proper modular test setup before the next release, fine. If we don't, I suggest to merge it anyway and create a separate issue for the modular integration tests.

After all, users shouldn't suffer because our test setup lags behind.

Thoughts?

**Comment by beatngu13** [comment] 2022-02-19 09:24
@scordio thx for the heads up! I already stumbled over [this](https://docs.gradle.org/7.3/userguide/java_testing.html#blackbox_integration_testing):

>In Eclipse, compiling multiple modules in one project is [currently not support](https://bugs.eclipse.org/bugs/show_bug.cgi?id=520667) [sic]. Therefore the integration test (blackbox) setup described here only  works in Eclipse if the tests are moved to a separate subproject.

I believe all maintainers are using IntelliJ IDEA, but this makes it harder for outside contributors who use Eclipse.

**Closed** 2022-02-21 10:02 UTC
Labels: 🐞 type: bug, 🚦 status: in progress, ⚙️ component: Pioneer, 📖 theme: extensions
