### ISSUE TITLE
Error when using Spring Boot 3

### ISSUE THREAD

**Issue by zelaskoa** [junit-pioneer/junit-pioneer#810] opened 2024-04-03 11:09 UTC
Hi when i try using JPioneer with latest Spring Boot 3.2.4 i get error

```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:99)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:63)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: org.junit.platform.commons.JUnitException: MethodSelector [className = ‘mycompany.MyTest’, methodName = ‘myTestSuccessfully', parameterTypes = '', classLoader = null] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:103)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:83)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 13 more
Caused by: java.lang.IllegalAccessError: class org.junit.platform.engine.discovery.MethodSelector tried to access private method 'java.lang.Class[] org.junit.platform.commons.util.ReflectionUtils.resolveParameterTypes(java.lang.Class, java.lang.String, java.lang.String)' (org.junit.platform.engine.discovery.MethodSelector and org.junit.platform.commons.util.ReflectionUtils are in unnamed module of loader 'app')
	at org.junit.platform.engine.discovery.MethodSelector.lazyLoadParameterTypes(MethodSelector.java:267)
	at org.junit.platform.engine.discovery.MethodSelector.lazyLoadJavaMethod(MethodSelector.java:247)
	at org.junit.platform.engine.discovery.MethodSelector.getJavaMethod(MethodSelector.java:207)
	at org.junit.jupiter.engine.discovery.MethodSelectorResolver.resolve(MethodSelectorResolver.java:90)
	at org.junit.jupiter.engine.discovery.MethodSelectorResolver.resolve(MethodSelectorResolver.java:75)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:150)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:189)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:126)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:92)
	... 18 more
```

**Comment by Michael1993** [comment] 2024-04-03 11:16
Hi @zelaskoa !

I am not sure if you are in the right place, I don't see Pioneer in that stack trace. Are you sure this is a Pioneer issue and not a JUnit 5 issue?

**Comment by Michael1993** [comment] 2024-04-03 11:18
A big hurdle when people update to Spring 3 is that it baselines against a Java version with stricter access controls - have you tried updating your JUnit 5 version?

I think newer JUnit versions might have already solved this issue.

**Comment by zelaskoa** [comment] 2024-04-03 11:20
Hi yes this was also my first thought. But after removing Pioneer Dependency and @DefaultTimeZone everything works again. I think latest spring boot version 3.2.4 already uses junit5  5.10.1 version

**Comment by Michael1993** [comment] 2024-04-03 11:24
Could you copy the versions of your relevant dependencies? I would also try to update Pioneer to its latest version.

**Comment by zelaskoa** [comment] 2024-04-03 11:30
sure: i see this dependencies in the dependency tree

+- org.springframework.boot:spring-boot-starter-test:jar:3.2.4:test
...|  
+- org.junit.jupiter:junit-jupiter:jar:5.10.1:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.10.1:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.10.1:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.10.1:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.10.1:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.10.1:test

and INFO] |  +- org.mockito:mockito-junit-jupiter:jar:5.7.0:test

and 

 +- org.junit-pioneer:junit-pioneer:jar:2.2.0:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.10.1:test
[INFO] |  |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  |  \- org.junit.platform:junit-platform-commons:jar:1.10.1:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-params:jar:5.10.1:test
[INFO] |  \- org.junit.platform:junit-platform-launcher:jar:1.10.1:test

**Comment by Michael1993** [comment] 2024-04-03 11:34
Thank you! I will take a look later.

In the meantime please try adding the JUnit BOM to your dependencies.

**Comment by Bukama** [comment] 2024-04-03 15:47
Just as an information: We already build against Junit 5.10.1

**Comment by beatngu13** [comment] 2024-04-03 20:56
I have created an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for this issue:

https://github.com/beatngu13/junit-pioneer-issue-810-mre

The test:

https://github.com/beatngu13/junit-pioneer-issue-810-mre/blob/bd82d53fed9eaf3fcf21d50ff2aca272690c549f/src/test/java/com/example/demo/JunitPioneerTests.java#L10-L18

The build:

https://github.com/beatngu13/junit-pioneer-issue-810-mre/actions/runs/8545330597/job/23413371466#step:4:734

Output of `mvn dependency:tree`:

```text
[INFO] com.example:demo:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter:jar:3.2.4:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:3.2.4:compile
[INFO] |  |  \- org.springframework:spring-context:jar:6.1.5:compile
[INFO] |  |     +- org.springframework:spring-aop:jar:6.1.5:compile
[INFO] |  |     +- org.springframework:spring-beans:jar:6.1.5:compile
[INFO] |  |     +- org.springframework:spring-expression:jar:6.1.5:compile
[INFO] |  |     \- io.micrometer:micrometer-observation:jar:1.12.4:compile
[INFO] |  |        \- io.micrometer:micrometer-commons:jar:1.12.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:3.2.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:3.2.4:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.4.14:compile
[INFO] |  |  |  \- ch.qos.logback:logback-core:jar:1.4.14:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.21.1:compile
[INFO] |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.21.1:compile
[INFO] |  |  \- org.slf4j:jul-to-slf4j:jar:2.0.12:compile
[INFO] |  +- jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
[INFO] |  +- org.springframework:spring-core:jar:6.1.5:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:6.1.5:compile
[INFO] |  \- org.yaml:snakeyaml:jar:2.2:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:3.2.4:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:3.2.4:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:3.2.4:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.9.0:test
[INFO] |  |  \- org.slf4j:slf4j-api:jar:2.0.12:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:4.0.2:test
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:2.1.3:test
[INFO] |  +- net.minidev:json-smart:jar:2.5.0:test
[INFO] |  |  \- net.minidev:accessors-smart:jar:2.5.0:test
[INFO] |  |     \- org.ow2.asm:asm:jar:9.3:test
[INFO] |  +- org.assertj:assertj-core:jar:3.24.2:test
[INFO] |  |  \- net.bytebuddy:byte-buddy:jar:1.14.12:test
[INFO] |  +- org.awaitility:awaitility:jar:4.2.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.10.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.10.2:test
[INFO] |  +- org.mockito:mockito-core:jar:5.7.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.14.12:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.3:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:5.7.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.1:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-test:jar:6.1.5:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.1:test
[INFO] \- org.junit-pioneer:junit-pioneer:jar:2.2.0:test
[INFO]    +- org.junit.jupiter:junit-jupiter-api:jar:5.10.2:test
[INFO]    |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO]    |  +- org.junit.platform:junit-platform-commons:jar:1.10.2:test
[INFO]    |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO]    +- org.junit.jupiter:junit-jupiter-params:jar:5.10.2:test
[INFO]    \- org.junit.platform:junit-platform-launcher:jar:1.10.2:test
[INFO]       \- org.junit.platform:junit-platform-engine:jar:1.10.2:test
```

---

@zelaskoa how does your project differ? Would you mind creating a corresponding MRE or create a PR in the aforementioned repo, which yields your exception?

**Comment by beatngu13** [comment] 2024-04-21 16:09
I'm gonna close this due to missing feedback. If you are still having trouble, feel free to re-open.

**Closed by beatngu13** 2024-04-21 16:09 UTC
Labels: 🏗️ type: question, 📖 theme: infrastructure, 🚦 status: works as designed, ⚙️ component: Jupiter
