### ISSUE TITLE
Build jobs sometimes timeout

### ISSUE THREAD

**Issue by Bukama** [junit-pioneer/junit-pioneer#324] opened 2020-08-17 17:28 UTC
In the last time several job builds timeout. As far as we can identify they are all Windows jobs at Java 11 or 14:

> Thanks for making me aware of this. The example job you posted is with Java 11 on Windows, and it looks like it timed out during the tests:
> 
> ```
> 2020-08-15T13:32:27.2087572Z > Task :processTestResources
> 2020-08-15T13:32:27.2087905Z > Task :testClasses
> 2020-08-15T13:32:57.2085938Z > Task :test
> 2020-08-15T19:30:51.8898754Z ##[error]The operation was canceled.
> 2020-08-15T19:30:51.9603377Z Post job cleanup.
> 2020-08-15T19:30:52.1317368Z Post job cleanup.
> 2020-08-15T19:30:54.1273868Z [command]"C:\Program Files\Git\bin\git.exe" version
> ```

> 
> [961045944 - win / java 11](https://github.com/junit-pioneer/junit-pioneer/pull/261/checks?check_run_id=961045944)
> 

>  [990846534 - win / java 14](https://github.com/junit-pioneer/junit-pioneer/runs/990846534)

**Comment by Bukama** [comment] 2020-09-12 08:54
[1105113930 - win / java 14](https://github.com/junit-pioneer/junit-pioneer/pull/326/checks?check_run_id=1105113930)

**Comment by nicolaiparlog** [comment] 2020-09-26 09:36
Too bad I don't have Windows set up for development to take a look at this. :cry: :grin: Looks like somebody else will have to check this out. :yum: 

And we should actually fix this!

**Comment by Bukama** [comment] 2020-09-26 10:17
Just as a reminder:
When fixing this `windows` has to be added to both, the main workflow and also the module build workflow.

**Comment by Michael1993** [comment] 2021-01-06 15:00
It's not just Windows! It seems ubuntu builds have been timing out as well.

**Comment by nipafx** [comment] 2021-01-12 20:16
I ran about 170k tests and I didn't take notice of any deadlocks (although if just a few threads lock, I wouldn't have noticed). This was on Gentoo with kernel version 5.9.16.

**Comment by nipafx** [comment] 2021-02-23 20:38
We've investigated this a bit and the only weird behavior we've discovered locally is that lots of classes are loaded and unloading blocks the JVM (0% CPU usage, etc) for a while. We could trace that back to the use of `EqualsVerifier` in `IssueTestCaseTests` and `IssueTestSuiteTests`.

Entire test suite (after ~100k tests):

![image](https://user-images.githubusercontent.com/6537432/108904724-27e03180-761f-11eb-9e06-df60603e6bf5.png)

Just the two tests (after ~14k tests):

![image](https://user-images.githubusercontent.com/6537432/108904013-4560cb80-761e-11eb-99a2-7d85b11642fd.png)

Test suite without them (after ~800k tests):

![image](https://user-images.githubusercontent.com/6537432/108903450-9de39900-761d-11eb-9a1c-ded338a0f575.png)

(All experiments done on Java 11.0.6, Gentoo, kernel 5.10.17.)

I'm doubtful this is the reason for the timeouts because I don't see how these pauses (however extreme they appear for unloading a few classes can occur on the CI server because I assume this only happens because `EqualsVerifier` creates so many proxy classes in the many thousands of test suite executions. How this could be a problem in a single suite execution is beyond me.

Still, I'll disable the corresponding tests, so we can see whether the build becomes more stable.

**Comment by nipafx** [comment] 2021-02-23 21:05
Just ran 1.4 million tests on 5d008d4 without any apparent problems. If the timeouts remain, we may need another test system to reproduce. Only other idea I have at the moment is to guess that concurrent test execution is the problem and blindly disable it to see whether that makes the build complete every time.

**Comment by nipafx** [comment] 2021-02-23 21:08
A cursory examination of `EqualsVerifier` (by a very nice and helpful viewer on Twitch) gives the impression that it may not be thread-safe. If 5d008d4 removed the timeouts, we could try to use `@ResourceLock` to execute `EqualsVerifier` tests sequentially.

**Comment by nipafx** [comment] 2021-02-23 21:09
Ok, that didn't fic the problem. We just had [a timeout on macos](https://github.com/junit-pioneer/junit-pioneer/pull/424/checks?check_run_id=1964783859) (for once, yay!).

**Comment by Bukama** [comment] 2021-04-13 15:57
related to #457 and #460 (that's why I assigned @Michael1993

**Comment by Michael1993** [comment] 2021-04-22 19:53
It is possible this issue is now solved. We shall never be sure.

**Comment by nipafx** [comment] 2021-04-23 13:02
Let's way for a few more PRs to come and go before closing this.

**Comment by nipafx** [comment] 2021-04-28 10:50
After about a dozen complete builds that were all successful, this problem appears to be fixed or at least greatly diminished.

Thank you @Michael1993 for spending time on this, I really appreciate it! You definitely deserve one of these: 🎖️ (Yes, it's the  _medal_military_ 😮 - basically, GitHub's purple heart.)

**Closed** 2021-04-28 10:50 UTC
Labels: ⚙️ component: Pioneer, 🐞 type: bug, 📖 theme: build, 🚦 status: reviewing, 🛸 3rd-party: Github Actions
