### ISSUE TITLE
NoClassDefError with JUnit Jupiter 5.7.0

### ISSUE THREAD

**Issue by fbiville** [junit-pioneer/junit-pioneer#343] opened 2020-09-28 15:26 UTC
Hi, I want to use 0.9.1 JUnit Pioneer's `@org.junitpioneer.jupiter.SetSystemProperty` but it currently fails with JUnit Jupiter 5.7.0:
```java
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven-deluxe/3.6.3-0/libexec
Java version: 11.0.8, vendor: N/A, runtime: /usr/local/Cellar/openjdk@11/11.0.8/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
[...]
WARNING: TestEngine with ID 'junit-jupiter' failed to execute tests
java.lang.NoClassDefFoundError: org/junit/platform/commons/util/UnrecoverableExceptions
	at org.junit.jupiter.engine.support.OpenTest4JAndJUnit4AwareThrowableCollector.createAbortedExecutionPredicate(OpenTest4JAndJUnit4AwareThrowableCollector.java:58)
	at org.junit.jupiter.engine.support.OpenTest4JAndJUnit4AwareThrowableCollector.<clinit>(OpenTest4JAndJUnit4AwareThrowableCollector.java:41)
	at org.junit.jupiter.engine.support.JupiterThrowableCollectorFactory.createThrowableCollector(JupiterThrowableCollectorFactory.java:34)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:78)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.commons.util.UnrecoverableExceptions
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more
```
It does **not** fail with JUnit Jupiter 5.6.2.

**Comment by Bukama** [comment] 2020-09-28 16:55
Hey @fbiville,
thanks for pointing this out! May I ask which Pioneer version you use?

To the JUnit 5.7.0 problem. They changed some of their classes, so the usage of the current Pioneer version (0.9.1) is not working. We have already seen some breaking changes in 5.6.0 in the Testkit Engine (see #320), but as those didn't break our public extension and we had no further need to upgrade, we didn't upgrade yet.

With this break in a public extension things change in my opinion, so we'll have a closer look.

**Comment by Bukama** [comment] 2020-09-28 17:56
In #345 I updated to 5.7.0 and I have no problems using this version with our current tests.

Can you provide a source code example which leads to the error above please?

**Comment by Bukama** [comment] 2020-09-28 18:02
> I am seeing this in my project. I do not use modules. I use the latest JUnit, 5.7.0. Here is a link to my CI builds if it helps https://github.com/project-ncl/build-finder/actions/runs/277109862.

Hi @dwalluck,
are you sure the link is correct? It links to a build where everything seems fine?

**Comment by dwalluck** [comment] 2020-09-28 18:04
@Bukama Check the log. The build somehow passes but test coverage is reported as 0% due to the error described in this issue.

**Comment by Bukama** [comment] 2020-09-28 18:13
Hmm, the listed exception is listed as an internal exception in the [JUnit 5 JavaDocs](https://junit.org/junit5/docs/snapshot/api/org.junit.platform.commons/org/junit/platform/commons/util/UnrecoverableExceptions.html). 

I'm curious where we use it (indirectly).

**Comment by dwalluck** [comment] 2020-09-28 18:57
@Bukama I found a difference, after upgrading from 0.9.0 -> 0.9.1 we have 

junit-platform-commons:jar:1.5.2:test

instead of

junit-platform-commons:jar:1.7.0:test

**Comment by dwalluck** [comment] 2020-09-28 19:01
@Bukama Introduced in https://github.com/junit-pioneer/junit-pioneer/commit/3b67f163f3fca8094211cb2bf93a3afef305a5c6, `build.gradle.kts` must be setting it to the wrong version?

**Comment by dwalluck** [comment] 2020-09-28 19:06
So now the `pom.xml` adds an explicit dependency on
 
```
<dependency>
      <groupId>org.junit.platform</groupId>
      <artifactId>junit-platform-commons</artifactId>
      <version>1.5.2</version>
      <scope>runtime</scope>
    </dependency>
```

I know I could add an exclusion to my build to workaround this now.

**Comment by dwalluck** [comment] 2020-09-28 19:58
So the issue is caused by mixed dependency versions. This happens because I only declared a few junit dependencies and not `junit-platform-commons` explicitly which got brought in transitively through junit-pioneer.

The way to prevent this is to depend on `junit-bom` instead of separate dependencies in my project as this will keep versions in sync with one another. See <https://github.com/project-ncl/build-finder/pull/229/files>.

**Comment by dwalluck** [comment] 2020-09-28 20:37
I don't think #345 is necessary. It appears to be an issue with my build. But, I may suggest you also use junit-bom to set the versions automatically instead of manually. I will make a PR.

**Comment by dwalluck** [comment] 2020-09-28 20:45
I have created #346. While, not a necessary change, it is probably safer to do so that the versions of jupiter and platform are automatically aligned for all possible dependencies.

**Comment by dwalluck** [comment] 2020-09-28 20:57
@fbiville I think you can fix this by adding `junit-bom` to your project. While it's briefly mentioned in https://junit.org/junit5/docs/current/user-guide/#dependency-metadata-junit-bom in neither the case of Maven or Gradle does it tell you how to actually do it. Add to your `pom.xml` and let us know if it fixes the issue for you:

```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.junit</groupId>
            <artifactId>junit-bom</artifactId>
            <version>5.7.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by Bukama** [comment] 2020-09-29 16:10
> @Bukama Introduced in [3b67f16](https://github.com/junit-pioneer/junit-pioneer/commit/3b67f163f3fca8094211cb2bf93a3afef305a5c6), `build.gradle.kts` must be setting it to the wrong version?

The version is set through the [project properties](https://github.com/junit-pioneer/junit-pioneer/blob/master/gradle.properties)  (current 5.2 => 5.5.2 & 1.5.2). The change (moving it from test dependency into compile dependency) was necessary to access public classes / methods.

**Comment by Bukama** [comment] 2020-09-29 16:12
> I don't think #345 is necessary. It appears to be an issue with my build.

Thanks for investigation!

**Comment by Bukama** [comment] 2020-09-29 18:41
We just postponed our 1.0.0 release (which was planed for this evening) and released 0.9.2 instead using a BOM to make sure the versions on our site are aligned.

@fbiville 
Please update to 0.9.2 and try the check suggestion from @dwalluck so we can see you problem has gone too and we can close this issue or if we have to do further work (maybe in cooperation with the JUnit Jupiter maintainers)

Again thank you both for the issue, investigation, PR an everything!

**Comment by fbiville** [comment] 2020-10-02 08:15
@Bukama sorry for the delay.

Adding the JUnit BOM to my own pom.xml fixes the issue.

Not adding the BOM and simply upgrading to JUnit Pioneer 0.9.2 does not solve the issue for me, the `java.lang.NoClassDefFoundError` still occurs in that case.

**Comment by sormuras** [comment] 2020-10-02 18:34
> Shall we seek out for the JUnit team to find a common solution

There is no spoon. Nor a common solution. It all depends on the build tool and its dependency resolution logic. Users should read the manual of the tool(s) they are using. We decided to link to a pair of them at https://junit.org/junit5/docs/current/user-guide/#dependency-metadata-junit-bom

Here's another good answer regarding a BOM-related question: https://stackoverflow.com/questions/54598484/gradle-5-junit-bom-and-spring-boot-incorrect-versions

**Comment by dwalluck** [comment] 2020-10-02 19:37
It just so happens that junit-pioneer is compatible with junit 5.7.0, even though a slightly older version is used in the project. I am not sure what could be done in the case where the junit bom in the user's project is not compatible with junit-pioneer.

In case the user is fine using the same version used in junit-pioneer, then it's always compatible and everything works fine. If the user wants to specify a different version then an API mismatch can occur as described here.

**Comment by dwalluck** [comment] 2020-10-02 19:38
It should be said that the problem described here was an API mismatch between jupiter and the platform, But, I suppose an API mismatch could also occur vs. junit-jupiter itself.

**Comment by beatngu13** [comment] 2020-10-03 11:04
>* Is it enough to put an advise in our docs
> 
>* Shall we seek out for the JUnit team to find a common solution

I'd go with @sormuras suggestions.

>* Shall we always align with JUnit (as of now we don't want to do that)

I think our current mantra is fine:

>Pioneer always depends on the lowest JUnit 5 version that supports its feature set, but that should not keep you from using 5's latest and greatest.

**Comment by nipafx** [comment] 2020-10-06 18:57
PR #346 Introduced BOM-based dependency management and PR #351 adds a note to the README. As far as I can tell, that's the best we can do for now. If the problem resurfaces, we may have to talk to the JUnit team about whether we can actually prevent this from happening.

**Closed by nipafx** 2020-10-06 18:57 UTC
Labels: ⚙️ component: Platform, 📖 theme: infrastructure, 🚦 status: waiting-for-feedback
