### ISSUE TITLE
generateChangelog task fails during release

### ISSUE THREAD

**Issue by beatngu13** [junit-pioneer/junit-pioneer#757] opened 2023-09-11 17:38 UTC
Happened during the release of v2.1.0:

https://github.com/junit-pioneer/junit-pioneer/actions/runs/6120763942/job/16613414149#step:4:80

Artifacts are available on Maven Central:

https://mvnrepository.com/artifact/org.junit-pioneer/junit-pioneer/2.1.0

However, due to the failed `generateChangelog` task, no tag and no GitHub release have been created.

**Comment by beatngu13** [comment] 2023-09-11 17:41
Tag manually created:

https://github.com/junit-pioneer/junit-pioneer/releases/tag/v2.1.0

**Comment by Michael1993** [comment] 2023-09-11 18:36
Duplicate of #730

**Closed** 2023-09-11 18:36 UTC
Labels: 🐞 type: bug, 📖 theme: build, 🚦 status: in progress, ⚙️ component: Pioneer, 🛸 3rd-party: Gradle
