### ISSUE TITLE
DefaultLocale/DefaultTimeZone - ExecutionMode

### ISSUE THREAD

**Issue by sdavids** [junit-pioneer/junit-pioneer#131] opened 2018-11-01 09:44 UTC
Both _DefaultLocale_ and _DefaultTimeZone_ can only be realistically used with [@Execution(SAME_THREAD)](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/parallel/ExecutionMode.html#SAME_THREAD) or a [ResourceLock](https://junit.org/junit5/docs/current/api/org/junit/jupiter/api/parallel/ResourceLock.html).

Maybe it should be enforced on a programmatic level?

Or their documentation should have pointers to Execution/ResourceLock.

See also:
https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution-synchronization

**Comment by sdavids** [comment] 2018-11-01 09:45
Execution was introduced in JUnit 5.3 whereas JUnit-Pioneer uses 5.1.1.

**Comment by sdavids** [comment] 2018-11-01 09:59
Maybe there is another way to indicate "this extension does not support @Execution(CONCURRENT)".

The [system properties extension](https://github.com/junit-pioneer/junit-pioneer/issues/129) will have the same issue.

**Comment by nicolaiparlog** [comment] 2019-10-21 22:27
We just faced the same issue in #110. Having a look at `@Execution(SAME_THREAD)` / `ResourceLock` in the context of `DefaultLocale` or `DefaultTimeZone`, I get the impression that this wouldn't work well as all tests using these extensions would run sequentially / lock on the same resource. Yet I see no other way to ensure correctness, so we might as well add `@Execution(SAME_THREAD)` and (a comment to Javadoc and documentation explaining the reason).

@marcphilipp, @sormuras: Did I get this right? If so, I will make the change after #110 got merged.

**Comment by marcphilipp** [comment] 2019-10-22 18:48
I think `@ResourceLock(value = LOCALE, mode = READ_WRITE)` should be enough so they could run in parallel with other tests that use different resources.

**Comment by nicolaiparlog** [comment] 2019-10-22 20:27
Makes sense. Will do that after #110.

**Comment by nicolaiparlog** [comment] 2019-11-01 14:11
Note to self:

* check all extensions whether they need this (e.g. #129/#133)
* consider documenting the approach

**Comment by sormuras** [comment] 2019-12-10 18:58
Is Pioneer already on 5.3?

**Comment by sormuras** [comment] 2019-12-10 19:19
Answer myself: yes.

https://github.com/junit-pioneer/junit-pioneer/blob/master/build.gradle.kts#L34

**Comment by Bukama** [comment] 2020-05-02 11:47
I had a view on this and enabled the [parallel execution](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution-config), so that the jupiter engine executes classes and methods inside the classes in parallel.

I then noticed following extensions / tests get flaky

* DefaultLocale
* DefaultTimeZone 
* SystemEnvironment
* SystemProperty (heavly)
* TempDir (heavly)
* PioneerAnnotationUtils (heavly)

I read the [synchronization docs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parallel-execution-synchronization) and tried several things (not all commited and pushed to #253), but they didn't make the tests stable.
So I have several questions.

My goal would be to annotate the annotations and doing this become independet of the indiviual settings the users have out there. Second goal is to achieve that the user does not have to worry about the execution, when writing his tests.

So I started with the `@ResourceLocks` which were mentioned here. There are locks for `Locale`, `TimeZone` and `SystemProperties`. 

I first used it on `@DefaultLocale` using `@ResourceLock(value = Resources.LOCALE, mode = ResourceAccessMode.READ_WRITE)`. But I'm not sure if this makes any differences as those tests weren't flaky at the beginning either.

When using the same for `@DefaultTimeZone` (`@ResourceLock(value = Resources.TIME_ZONE, mode = ResourceAccessMode.READ_WRITE)`) it helps, but not always.
There is still one test (`shouldExecuteTestsWithConfiguredTimeZone`) which quite often fails (like about in 20% of executions). Most with one of those messages (values may change due parallelism)
 
```
Expecting:
 <sun.util.calendar.ZoneInfo[id="America/Los_Angeles",offset=-28800000,dstSavings=3600000,useDaylight=true,transitions=185,lastRule=java.util.SimpleTimeZone[id=America/Los_Angeles,offset=-28800000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=3,startMonth=2,startDay=8,startDayOfWeek=1,startTime=7200000,startTimeMode=0,endMode=3,endMonth=10,endDay=1,endDayOfWeek=1,endTime=7200000,endTimeMode=0]]>
to be equal to:
 <sun.util.calendar.ZoneInfo[id="UTC",offset=0,dstSavings=0,useDaylight=false,transitions=0,lastRule=null]>
but was not.


Expecting:
 <en_en>
to be equal to:
 <custom>
but was not.

```

This is also the case then setting the `@ResourceLock` on top of the test class instead at the annotations. Same for the lock to lock `SystemProperty`.

For the others extensions I tried to annotate them with `@Execution(SAME_THREAD)` like in the `@RepeatFailedTest` but this didn't help to make the tests stable. I tried to place them on test class level, on annotation level of the singular annotations, of the repeatable plural annotations (and both).

So I have several questions about **WHERE** to place the `@ResourceLock` and `@Execution(SAME_THREAD)` annotations so that they _should_ work:

1. Annotation? What about repeatable - do they have to be at the singluar one or the plural ones?
2. Extension implementation? What about parameter resolvers etc.?
3. At test class level? What about inner classes?

I know that concurrent execution is an experimental feature, that's why I ask what's the intendend way is.

@marcphilipp @sormuras Can you give me some information about that? Docs are not clear (at least not for me) at this point.

**Comment by marcphilipp** [comment] 2020-05-02 13:22
The problem is that the executions you trigger via `EngineTestKit` also pick up the configuration parameters, i.e. also run in parallel. If you add `.configurationParameter("junit.jupiter.execution.parallel.enabled", "false")` in `ExecutionResults` and `@ResourceLock(Resources.LOCALE)` to `DefaultLocaleTests` most of the failures go away. I think this is unexpected when using `EngineTestKit` and JUnit should not do this be default. Could you please open an issue for that in the junit5 repo?

The remainder of the failures (on my machine) are now in `TempDirectoryExtensionTests` which uses a lot of static variables so I refrained to `@Execution(ExecutionMode.SAME_THREAD)`. With that all tests pass.

> So I have several questions about **WHERE** to place the `@ResourceLock` and `@Execution(SAME_THREAD)` annotations so that they _should_ work:
> 
>     1. Annotation? What about repeatable - do they have to be at the singluar one or the plural ones?

If you use it as a meta-annotation on a `@Repeatable` annotation you should put it on both annotations due to the way annotation lookup works for repeatable annotations in `AnnotationSupport`.

>     2. Extension implementation? What about parameter resolvers etc.?

Both annotations need to be present or meta-present on test methods or classes. Thus, putting them on the extension implementation class won't help.

>     3. At test class level? What about inner classes?

Both annotations take effect for the whole subtree, i.e. putting `@ResourceLock("foo")` on a top-level test classes means all test methods in that class, all `@Nested` classes and their tests methods, recursively, require that resource. Similarly, `@ExecutionMode(SAME_THREAD)` forces the whole subtree to use the same thread.

**Comment by Bukama** [comment] 2020-05-02 14:56
Thank you very much @marcphilipp for the information! I've created an issue for you (_OK actually two - one more for documentation 👼 _).

**Comment by nicolaiparlog** [comment] 2020-06-20 10:00
This issue spawned: #274, #276, and #277.

**Closed** 2020-08-05 10:28 UTC
Labels: 🐞 type: bug, 📖 theme: concurrency, 📖 theme: extensions, 🚦 status: in-progress
